name: com.example.simple_cubit_app
description: A simple Flutter application demonstrating the Cubit pattern for state management. The app displays a text with an icon, and switches the text and icon when clicked.
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true